#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rvm
Version  : 1.11.3.9
Release  : 3
URL      : https://rubygems.org/downloads/rvm-1.11.3.9.gem
Source0  : https://rubygems.org/downloads/rvm-1.11.3.9.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# rvm
http://rvm.io/
## Description
RVM ~ Ruby Environment Manager ~ Ruby Gem Library

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rvm-1.11.3.9
gem spec %{SOURCE0} -l --ruby > rubygem-rvm.gemspec

%build
gem build rubygem-rvm.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rvm-1.11.3.9.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rvm-1.11.3.9.gem
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/Object/arguments_for_install-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/Object/normalize_argument-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/Object/quote-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/Object/ruby%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/cdesc-AliasWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/create-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/AliasWrapper/show-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/archives-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/cdesc-CleanupWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/everything-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/logs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/repos-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/repositories-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/sources-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/CleanupWrapper/src-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ConfigMixin/cdesc-ConfigMixin.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ConfigMixin/clear_config%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ConfigMixin/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ConfigMixin/merge_config%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/EnvWrapper/cdesc-EnvWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/EnvWrapper/contents-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/EnvWrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/EnvWrapper/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/EnvWrapper/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/EnvWrapper/to_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/EnvWrapper/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/GlobalCacheHelper/cdesc-GlobalCacheHelper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/GlobalCacheHelper/disable%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/GlobalCacheHelper/enable%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/GlobalCacheHelper/enabled%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/GlobalCacheHelper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/cdesc-GemsetWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/create-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/empty-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/export-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/globalcache-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/import-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/pristine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/prune-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/use%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/GemsetWrapper/use-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/cdesc-ListWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/default-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/expand_variants-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/expanded_known-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/from_svn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/gemsets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/installable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/installed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/known_strings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/raw_known-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/raw_ruby_svn_tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/rubies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/ruby_svn_tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ListWrapper/strings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ToolsWrapper/cdesc-ToolsWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ToolsWrapper/expand_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ToolsWrapper/identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ToolsWrapper/identifier_for_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ToolsWrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ToolsWrapper/path_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ToolsWrapper/strings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/alias_create-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/alias_delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/alias_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/alias_show-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/aliases-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/cdesc-Environment.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/chdir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/compatible_with_current%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/config_value_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/config_value_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/current-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/current_environment_id-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/current_ruby_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/default_rvm_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/default_wrappers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/define_config_accessor-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/defined_config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/env_contents-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/env_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/environment_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/environment_with_gemset-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/exec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/expanded_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/extract_environment%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/extract_identifier%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/extract_options%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_create-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_empty-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_export-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_globalcache-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_import-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_initial-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_pristine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_prune-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_use%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/gemset_use-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/hash_to_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/identifier_to_gemset_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/identifier_to_ruby_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/install-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/list_default-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/list_gemsets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/list_known-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/list_known_strings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/list_ruby_svn_tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/list_strings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/normalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/normalize_array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/normalize_listing_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/normalize_option_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/normalize_ruby_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/normalize_set_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/path_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/perform_set_operation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/rake-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/rearrange_options%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/remove-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/reset_current%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ruby-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ruby_eval-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ruby_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/ruby_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/rvm-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/shell_wrapper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/source_rvm_environment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/specs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/system-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/tests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/tools-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/tools_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/tools_path_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/tools_strings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/uninstall-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/use%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/use-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/use_env_from_result%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/use_from_path%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/use_rvm_environment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/which-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/wrapper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Environment/wrapper_path_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/ErrorLoadingRVMRC/cdesc-ErrorLoadingRVMRC.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/ErrorWithResult/cdesc-ErrorWithResult.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/ErrorWithResult/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/ErrorWithResult/result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/IncompatibleRubyError/cdesc-IncompatibleRubyError.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/IncompleteCommandError/cdesc-IncompleteCommandError.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/cdesc-AbstractWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/command_complete%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/invoke_setup%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/raw_stdout_to_parts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/run_command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/run_command_silently-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/run_silently-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/shell_executable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/silent_command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/source_command_wrapper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/AbstractWrapper/wrapped_command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/cdesc-Result.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/exit_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/raw_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/stderr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/stdout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Result/successful%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/SingleShotWrapper/cdesc-SingleShotWrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/SingleShotWrapper/current-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/SingleShotWrapper/run_command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/SingleShotWrapper/run_command_silently-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/SingleShotWrapper/stderr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/SingleShotWrapper/stdin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/SingleShotWrapper/stdout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/SingleShotWrapper/with_shell_instance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Utility/build_cli_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Utility/cdesc-Utility.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Utility/escape_argument-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/Utility/escape_arguments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/cdesc-Shell.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/default_wrapper%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/Shell/default_wrapper-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/cache_method_call-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/cdesc-RVM.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/current-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/environment-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/environments-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/merge_config%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/method_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/path%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/RVM/reset_current%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/lib/rvm/shell/page-calculate_rvm_path_sh.ri
/usr/lib64/ruby/gems/2.2.0/doc/rvm-1.11.3.9/ri/lib/rvm/shell/page-shell_wrapper_sh.ri
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/History.md
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/Manifest.yml
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/alias.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/cleanup.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/configuration.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/env.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/gemset.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/info.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/list.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/rubies.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/sets.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/tools.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/utility.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/environment/wrapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/install_command_dumper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/shell.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/shell/abstract_wrapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/shell/calculate_rvm_path.sh
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/shell/result.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/shell/shell_wrapper.sh
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/shell/single_shot_wrapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/shell/utility.rb
/usr/lib64/ruby/gems/2.2.0/gems/rvm-1.11.3.9/lib/rvm/version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rvm-1.11.3.9.gemspec
